<a href="https://colab.research.google.com/github/praiseandrews/Data-Science-Learning/blob/main/02_NumPy_Practice/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("===== ARRAYS =====")

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("First Element:", arr[0])
print("Array Shape:", arr.shape)

print("\n===== MATRIX OPERATIONS =====")

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nAddition:")
print(matrix1 + matrix2)

print("\nMultiplication:")
print(matrix1 * matrix2)

print("\n===== MATHEMATICAL FUNCTIONS =====")

numbers = np.array([1, 2, 3, 4, 5])

print("Square:", np.square(numbers))
print("Square Root:", np.sqrt(numbers))
print("Exponential:", np.exp(numbers))

print("\n===== STATISTICAL CALCULATIONS =====")

data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))
print("Standard Deviation:", np.std(data))

===== ARRAYS =====
Array: [10 20 30 40 50]
First Element: 10
Array Shape: (5,)

===== MATRIX OPERATIONS =====
Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Addition:
[[ 6  8]
 [10 12]]

Multiplication:
[[ 5 12]
 [21 32]]

===== MATHEMATICAL FUNCTIONS =====
Square: [ 1  4  9 16 25]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

===== STATISTICAL CALCULATIONS =====
Mean: 30.0
Median: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951
